### ISSUE TITLE
Add support for horizontal scrollbar

### ISSUE THREAD

**Issue by pkhetrapal** [ludicrousxyz/ctrl-tab#27]

**Comment by nahtnam** [comment]
Great idea, I've been thinking about implementing this pretty soon (to support smaller sizes). I was thinking to add an option "Dynamic" and "Static" in the settings. Dynamic would remain as it is right now. As you add more blocks, the rest shrink. However, static would mean each block is 1/5 or 1/4th of the page and as you add more, a horizontal slide shows up.

WDYT?

**Comment by nahtnam** [comment]
I think in general I need to improve the UI but I think this is a good step towards usability on smaller devices

**Comment by c-ciobanu** [comment]
Hey, I personally prefer a vertical slide on desktop since is more usable than scrolling horizontally.
On mobile it could show only the titles and then on click expand.
That's my 2 cents.

**Comment by nahtnam** [comment]
I'm not sure vertical sliding would look that great because each tile is vertical so youd have to scroll really far to have the next tile in view.

I was thinking maybe adding something like this for those who prefer vertical scrolling:
![tabbie](https://cloud.githubusercontent.com/assets/1415847/7947591/5ebce982-097e-11e5-99b8-2ceb979dfda7.png)

The horizontal scrolling would be for people with small macbooks where they could use the trackpad to slide write and see more.

**Comment by nahtnam** [comment]
Hey sorry for the late reply. We have already implemented this in our new version of the extension! I'm trying to get the BETA out as soon as possible, ill update the old chrome extension with more details as I get closer
